title: Kubernetes Data Platform
description: >-
  KDP(Kubernetes Data Platform) delivers a modern, hybrid and cloud-native data platform based on Kubernetes.
#markdown: GFM
plugins:
    - jekyll-remote-theme

remote_theme: zendesk/jekyll-theme-zendesk-garden@main
search_enabled: true
sidebar:
  - label: Getting Started
    children:
      - overview_en
      - quick_start_en
      - advanced_install_en

# remote_theme: pages-themes/cayman@v0.2.0
# show_downloads: false