title: Kubernetes Data Platform
description: >-
  KDP(Kubernetes Data Platform) delivers a modern, hybrid and cloud-native data platform based on Kubernetes.
#markdown: GFM
plugins:
    - jekyll-remote-theme
    - jekyll-sitemap
    - jekyll-seo-tag
    - jemoji

remote_theme: vaibhavvikas/jekyll-theme-minimalistic
logo: 'https://linktime-public.oss-cn-qingdao.aliyuncs.com/linktime-homepage/kdp/kdp-logo.png'
platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/linktimecloud/kubernetes-data-platform
navigation:
  - name: Home
    link: ./index.html
  - name: Overview
    link: ./docs/zh/getting-started/overview.html

# remote_theme: pages-themes/cayman@v0.2.0
# show_downloads: false