title: Kubernetes Data Platform
description: >-
  KDP(Kubernetes Data Platform) delivers a modern, hybrid and cloud-native data platform based on Kubernetes.
markdown: GFM
plugins:
    - jekyll-remote-theme

remote_theme: sighingnow/jekyll-gitbook
syntax_highlighter_style: colorful
toc:
    enabled: true
    h_min: 1
    h_max: 3

# remote_theme: pages-themes/cayman@v0.2.0
# show_downloads: false