title: Kubernetes Data Platform
description: >-
  KDP(Kubernetes Data Platform) delivers a modern, hybrid and cloud-native data platform based on Kubernetes.
markdown: GFM
plugins:
    - jekyll-remote-theme

remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: auto
logo: https://linktime-public.oss-cn-qingdao.aliyuncs.com/linktime-homepage/kdp/kdp-logo.png
platforms:
  - name: GitHub
    link: https://github.com/linktimecloud/kubernetes-data-platform
  - name: LinkTime Cloud
    link: https://www.linktimecloud.com/
navigation:
  - name: Home
    link: ./README.html
    sublist:
      - name: Getting Started
        link: ./README.html#Getting Started
      - name: Community
        link: ./README.html#Community
      - name: Contributing
        link: ./README.html#Contributing
      - name: Code of Conduct
        link: ./README.html#Code of Conduct
  - name: Getting Started
    link: ./docs/en/overview/index.html
    sublist:
      - name: Architecture
        link: ./docs/en/overview/overview.html#Architecture
      - name: Advantages
        link: ./docs/en/overview/overview.html#Advantages
      - name: Highlights
        link: ./docs/en/overview/overview.html#Highlights
      - name: Quick Start
        link: ./docs/en/overview/overview.html#Quick\ Start
      - name: Advanced Installation
        link: ./docs/en/overview/overview.html#Advanced\ Installation
  - name: Catalogs
    link: ./docs/en/catalog-overview/catalogs.html
  - name: Developer Guide
    link: ./docs/en/developer-guide/developer-guide.html


#remote_theme: granbom/jekyll-theme-bootstrap4-navbar-cdn

# remote_theme: pages-themes/cayman@v0.2.0
# show_downloads: false

# remote_theme: "jeffreytse/jekyll-theme-yat"
# favicon: "https://linktime-public.oss-cn-qingdao.aliyuncs.com/linktime-homepage/kdp/kdp-logo-small.png"
# defaults:
#   home:
#     heading: "Kubernetes Data Platform"
#     subheading: "KDP(Kubernetes Data Platform) delivers a modern, hybrid and cloud-native data platform based on Kubernetes."
#     banner: "https://linktime-public.oss-cn-qingdao.aliyuncs.com/linktime-homepage/kdp/kdp-banner-en.png"